version: "2"

plugins:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
    exclude_patterns:
      - README.md
  markdownlint:
    enabled: false
  shellcheck:
    enabled: true
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:

#  flog:
#    enabled: true
#    config:
#      score_threshold: 20.0
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 25
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.

exclude_paths:
  - tmp/**/*
  - vendor/**/*
  - log/**/*
  - db/**/*
  - .bundle/
  - benchmarks/**/*
