version: "2"
plugins:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
    exclude_patterns:
      - config/engines.yml
  markdownlint:
    enabled: true
    checks:
      MD002: # "First header should be a h1 header"
        enabled: false
  shellcheck:
    enabled: true
  rubocop:
    enabled: true

  flog:
    enabled: true
    config:
      score_threshold: 20.0

exclude_paths:
  - tmp/**/*
  - vendor/**/*
  - log/**/*
  - db/**/*
  - .bundle/
  - benchmarks/**/*
